# This is a basic workflow to help you get started with Actions

name: 4 - Build Manually
run-name: ${{ github.actor }} Build Manually of branche ${{ github.ref_name }}

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Tag Image version. ex: 1.0.0'     
        required: true
        default: '1.0.0'

jobs:
  BuildDockerImage:
    name: Build and push Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.event.inputs.imageVersion }}
            ghcr.io/${{ github.repository }}:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}